apiVersion: v1  # Run with kubectl apply -f ubuntu_testing_pod.yml
kind: Pod
metadata:
  name: your-pod-name  # Replace 'your-pod-name' with the desired name for your Pod
  namespace: your-namespace  # Replace 'your-namespace' with the desired namespace
  labels:
    app: ubuntu
spec:
  containers:
  - image: ubuntu
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always